version: '3.7'

services:
  mirakurun-chinachu:
    build:
      context: ./docker/
    container_name: mirakurun-chinachu
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
    ports:
      # mirakurun
      - 40772:40772
      - 9229:9229
      # chinachu
      - 10772:10772
      - 20772:20772
    devices:
      # for card reader USB
      - /dev/bus:/dev/bus
      # pt3
      - /dev/pt3video0:/dev/pt3video0
      - /dev/pt3video1:/dev/pt3video1
      - /dev/pt3video2:/dev/pt3video2
      - /dev/pt3video3:/dev/pt3video3
    volumes:
      # mirakurun
      - ./mirakurun/run/:/var/run/
      - ./mirakurun/opt/:/opt/
      - ./mirakurun/config/:/app-config/
      - ./mirakurun/data/:/app-data/
      # chinachu
      - ./chinachu/rules.json:/Chinachu/rules.json
      - ./chinachu/data/:/Chinachu/data/
      - /home/Chinachu/recorded/:/Chinachu/recorded/
      - /home/Chinachu/tmp/:/Chinachu/tmp/
      # Optional
      - ./chinachu/recordedScripts/:/recordedScripts/
      - ./chinachu/ssh/:/root/.ssh/
    restart: always

